version: '3.2'

services:   
  proxy:
    image: nginx:alpine
    networks:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  serveur1:
    build: './serveur1/'
    networks:
      - frontend
      - serv1
  serveur2:
    build: './serveur2/'
    networks:
      - frontend
      - serv2
  php1:
    build: './serveur1/php/'
    networks:
      - serv1
    volumes:
      - ./serveur1/html:/usr/local/apache2/htdocs
  php2:
    build: './serveur2/php/'
    networks:
      - serv2
    volumes:
      - ./serveur2/html:/usr/local/apache2/htdocs/
  mariadb1:
    image: mariadb
    networks:
      - serv1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword 
  mariadb2:
    image: mariadb
    networks:
      - serv2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword 
networks:
  serv1:
  serv2:
  frontend:
